version: "3.1"

services:
   php:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 80:80
      volumes:
         - ./:/var/www/html
         - ./apache:/etc/apache2/sites-available

   database:
      image: mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - mariadb-data:/var/lib/mariadb

   adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080

volumes:
   mariadb-data: